# New ports collection makefile for:   herbstluftwm
# Date created:        24 February 2012
# Whom:                Christian Brassat
#
# $FreeBSD$
#

PORTNAME=      herbstluftwm
PORTVERSION=   0.2
PORTREVISION=  1
CATEGORIES=    x11-wm
MASTER_SITES=  http://wwwcip.cs.fau.de/~re06huxa/herbstluftwm/tarballs/

MAINTAINER=    crshd@mail.com
COMMENT=       herbstluftwm is a manual tiling window manager for X11

USE_XORG=      x11

USE_GMAKE=     yes

PLIST_FILES=   bin/herbstluftwm \
               bin/herbstluftclient

.include <bsd.port.mk>
