# $FreeBSD$

PORTNAME=      herbstluftwm
PORTVERSION=   0.4
PORTREVISION=  1
CATEGORIES=    x11-wm
MASTER_SITES=  http://wwwcip.cs.fau.de/~re06huxa/herbstluftwm/tarballs/

MAINTAINER=    crshd@mail.com
COMMENT=       herbstluftwm is a manual tiling window manager for X11

USE_XORG=      x11

USE_GMAKE=     yes

.include <bsd.port.mk>
