# New ports collection makefile for: fb
# Date created:        30 August 2012
# Whom:                Christian Brassat
#
# $FreeBSD$
#

PORTNAME=      fb
PORTVERSION=   1.0.5
PORTREVISION=  1
CATEGORIES=    www
MASTER_SITES=  http://paste.xinu.at/data/client/

MAINTAINER=    crshd@mail.com
COMMENT=       Command-line utility to create and manage pastes at paste.xinu.at

USE_GMAKE=     yes

PLIST_FILES=   bin/fb \
               lib/fb-client \
               lib/fb-client/fb-helper \
               share/man/man1/fb.1

.include <bsd.port.mk>
